/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl.java;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ba _Tran
 */
public class them_chiSoDien extends javax.swing.JFrame {

    private static them_chiSoDien frameThemChiSoDien;
    
    public static void openFrameThemChiSoDien() {
        frameThemChiSoDien = new them_chiSoDien();
        frameThemChiSoDien.setVisible(true);
        DateFormat df_MM = new SimpleDateFormat("MM");
        DateFormat df_yyyy = new SimpleDateFormat("yyyy");
        Calendar c = Calendar.getInstance();
        Date date = c.getTime();
        frameThemChiSoDien.label_thangHienTai.setText(df_MM.format(date));
        frameThemChiSoDien.label_namHienTai.setText(df_yyyy.format(date));
        
    }
    /**
     * Creates new form them_chiSoDien
     */
    public them_chiSoDien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_tuKhoa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label_thangHienTai = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_namHienTai = new javax.swing.JLabel();
        txt_chiSoMoi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        label_hoTenKH = new javax.swing.JLabel();
        label_soCongTo = new javax.swing.JLabel();
        label_soCMT = new javax.swing.JLabel();
        label_soDienThoai = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_phuongCuTru = new javax.swing.JLabel();
        label_diaChi = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        button_dong = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        comboBox_tuyChonTimKiem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        label_maKH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm chỉ số điện");

        txt_tuKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tuKhoaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Họ tên:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Số công tơ:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Số điện thoại:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Phường cư trú:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Số chứng minh thư:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Chỉ số điện THÁNG");

        label_thangHienTai.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_thangHienTai.setForeground(new java.awt.Color(255, 0, 0));
        label_thangHienTai.setText("...");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 255));
        jLabel12.setText("NĂM");

        label_namHienTai.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_namHienTai.setForeground(new java.awt.Color(255, 0, 0));
        label_namHienTai.setText("...");

        txt_chiSoMoi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_chiSoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chiSoMoiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("kWh");

        label_hoTenKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_hoTenKH.setText("...");

        label_soCongTo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_soCongTo.setText("...");

        label_soCMT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_soCMT.setText("...");

        label_soDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_soDienThoai.setText("...");

        label_email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_email.setText("...");

        label_phuongCuTru.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_phuongCuTru.setText("...");

        label_diaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_diaChi.setText("...");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        button_dong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_dong.setText("Đóng");
        button_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dongActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 204));
        jLabel23.setText(":");

        comboBox_tuyChonTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboBox_tuyChonTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã khách hàng", "Số công tơ" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Tìm khách hàng theo:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Mã khách hàng:");

        label_maKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_maKH.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comboBox_tuyChonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_tuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_thangHienTai)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(label_namHienTai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_chiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(button_dong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_hoTenKH)
                            .addComponent(label_soCongTo)
                            .addComponent(label_soCMT)
                            .addComponent(label_soDienThoai)
                            .addComponent(label_email)
                            .addComponent(label_phuongCuTru)
                            .addComponent(label_diaChi)
                            .addComponent(label_maKH))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBox_tuyChonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(txt_tuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(label_hoTenKH))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(label_soCongTo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(label_soCMT))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(label_soDienThoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(label_email))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(label_phuongCuTru))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(label_diaChi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(label_thangHienTai)
                            .addComponent(jLabel12)
                            .addComponent(label_namHienTai)
                            .addComponent(jLabel14)
                            .addComponent(jLabel23)
                            .addComponent(txt_chiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_dong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_maKH))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tuKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tuKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tuKhoaActionPerformed

    private void txt_chiSoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chiSoMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chiSoMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String where = "1";
        int tuyChonTimKiem = comboBox_tuyChonTimKiem.getSelectedIndex();
        
        switch(tuyChonTimKiem) {
            case 0:
                where = "idKH = " + txt_tuKhoa.getText();
            break;
            
            case 1:
                where = "soCongTo = " + txt_tuKhoa.getText();
            break;
        }
        
        label_maKH.setText("..");
        label_hoTenKH.setText("..");
        label_soCongTo.setText("..");
        label_soCMT.setText("..");
        label_soDienThoai.setText("..");
        label_email.setText("..");
        label_diaChi.setText("..");
        label_phuongCuTru.setText("..");
        
        String columns[] = new String[] {"idKH", "hoTen", "soCongTo", "soCMT", "soDienThoai", "email", "diaChi", "tenPhuong"};
        String table = "khachhang";
        
        String data[][] = DB_MySQL.select(columns, table, where);
        
        if(data != null) {
            
            label_maKH.setText(data[0][0]);
            label_hoTenKH.setText(data[0][1]);
            label_soCongTo.setText(data[0][2]);
            label_soCMT.setText(data[0][3]);
            label_soDienThoai.setText(data[0][4]);
            label_email.setText(data[0][5]);
            label_diaChi.setText(data[0][6]);
            label_phuongCuTru.setText(data[0][7]);
            
        } else 
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng yêu cầu !", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dongActionPerformed
        frameThemChiSoDien.setVisible(false);
    }//GEN-LAST:event_button_dongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c = Calendar.getInstance();
        Date date = c.getTime();
        
        if(Check_String.check(txt_chiSoMoi.getText(), Check_String.NUMBER)) {
            
            if(label_maKH.getText() != "...") {
            
                if(DB_MySQL.select(new String[] {"chiSoMoi"}, "chisodien", "idKH = " + label_maKH.getText())[0][0].charAt(0) == '0' && DB_MySQL.select(new String[] {"chiSoMoi"}, "datenhapchiso", "idKH = " + label_maKH.getText())[0][0].equals("0000-00-00")) {

                    if((Float.parseFloat(txt_chiSoMoi.getText()) > 0)  && (Float.parseFloat(txt_chiSoMoi.getText()) > Float.parseFloat(DB_MySQL.select(new String[] {"chiSoCu"}, "chisodien", "idKH = " + label_maKH.getText())[0][0]))) {

                        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm chỉ số điện ?", "Xác nhận", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {

                            DB_MySQL.update("chisodien", new String[] {"chiSoMoi"}, new String[] {txt_chiSoMoi.getText()}, "idKH = " + label_maKH.getText());
                            DB_MySQL.update("datenhapchiso", new String[] {"chiSoMoi"}, new String[] {df.format(date)}, "idKH = " + label_maKH.getText());
                            JOptionPane.showMessageDialog(this, "Thêm chỉ số mới thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            txt_chiSoMoi.setText("");

                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Chỉ số mới phải > 0 và > " + Float.parseFloat(DB_MySQL.select(new String[] {"chiSoCu"}, "chisodien", "idKH = " + label_maKH.getText())[0][0]) + " (chỉ số cũ)", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Khách hàng đã tồn tại chỉ số điện mới " + DB_MySQL.select(new String[] {"chiSoMoi"}, "datenhapchiso", "idKH = " + label_maKH.getText())[0][0], "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Chưa có khách hàng", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            
        } else
            JOptionPane.showMessageDialog(this, "Chỉ số điện mới phải là số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(them_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(them_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(them_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(them_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new them_chiSoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_dong;
    private javax.swing.JComboBox<String> comboBox_tuyChonTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label_diaChi;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_hoTenKH;
    private javax.swing.JLabel label_maKH;
    private javax.swing.JLabel label_namHienTai;
    private javax.swing.JLabel label_phuongCuTru;
    private javax.swing.JLabel label_soCMT;
    private javax.swing.JLabel label_soCongTo;
    private javax.swing.JLabel label_soDienThoai;
    private javax.swing.JLabel label_thangHienTai;
    private javax.swing.JTextField txt_chiSoMoi;
    private javax.swing.JTextField txt_tuKhoa;
    // End of variables declaration//GEN-END:variables
}
