/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package btl.java;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ba _Tran
 */
public class them_khachHang extends javax.swing.JFrame {
    
    private static them_khachHang frameThemKhachHang;
    /** Creates new form them_nguoiDung */
    
    public static void openFrameThemKhachHang() {
        frameThemKhachHang = new them_khachHang();
        frameThemKhachHang.setVisible(true);
        
    }
    
    public them_khachHang() {
        initComponents();
        radioButton_tinhTheoBac.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radioButton_tinhTheoBac = new javax.swing.JRadioButton();
        radioButton_tinhTheoDonGia = new javax.swing.JRadioButton();
        txt_donGiaDien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        txt_ngaySinh = new javax.swing.JTextField();
        txt_soCMT = new javax.swing.JTextField();
        txt_dienThoai = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        comboBox_phuong = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        button_tao = new javax.swing.JButton();
        button_dong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_diaChi = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txt_chiSoHienTai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboBox_gioiTinh = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txt_soCongTo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tạo khách hàng mới");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Họ tên: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Ngày sinh: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Số chứng minh/căn cước: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Số điện thoại: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Email: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Phường cư trú: ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Địa chỉ: ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Cách thức tính tiện điện: ");

        buttonGroup1.add(radioButton_tinhTheoBac);
        radioButton_tinhTheoBac.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_tinhTheoBac.setText("Tính theo bậc ( thông thường )");
        radioButton_tinhTheoBac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButton_tinhTheoBacItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioButton_tinhTheoDonGia);
        radioButton_tinhTheoDonGia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_tinhTheoDonGia.setText("Theo đơn giá cố định:");
        radioButton_tinhTheoDonGia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButton_tinhTheoDonGiaItemStateChanged(evt);
            }
        });
        radioButton_tinhTheoDonGia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                radioButton_tinhTheoDonGiaPropertyChange(evt);
            }
        });

        txt_donGiaDien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("VNĐ/số điện");

        txt_hoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_ngaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_soCMT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_dienThoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        comboBox_phuong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboBox_phuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa chọn", "Cầu Diễn", "Đại Mỗ", "Mễ Trì", "Mỹ Đình 1", "Mỹ Đình 2", "Phương Canh", "Phú Đô", "Trung Văn", "Tây Mỗ", "Xuân Phương" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("yyyy-mm-dd");

        button_tao.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_tao.setText("Tạo");
        button_tao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_taoActionPerformed(evt);
            }
        });

        button_dong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_dong.setText("Đóng");
        button_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dongActionPerformed(evt);
            }
        });

        txt_diaChi.setColumns(20);
        txt_diaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_diaChi.setLineWrap(true);
        txt_diaChi.setRows(3);
        jScrollPane1.setViewportView(txt_diaChi);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Chỉ số hiện tại: ");

        txt_chiSoHienTai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_chiSoHienTai.setText("0");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("kWh");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Giới tính:");

        comboBox_gioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboBox_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa chọn", "Nam", "Nữ" }));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Số công tơ: ");

        txt_soCongTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soCongToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(button_tao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(button_dong, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                    .addComponent(txt_soCMT)
                                    .addComponent(txt_dienThoai)
                                    .addComponent(txt_email)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(comboBox_phuong, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_soCongTo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioButton_tinhTheoDonGia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_donGiaDien, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addComponent(radioButton_tinhTheoBac)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_chiSoHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(112, 112, 112)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboBox_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_soCMT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBox_phuong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_soCongTo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButton_tinhTheoDonGia)
                            .addComponent(txt_donGiaDien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(radioButton_tinhTheoBac)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_chiSoHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_dong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_tao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_soCongToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soCongToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soCongToActionPerformed

    private void button_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dongActionPerformed
        frameThemKhachHang.setVisible(false);
    }//GEN-LAST:event_button_dongActionPerformed

    private void button_taoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_taoActionPerformed
        
        String hoTen = txt_hoTen.getText();
        
        String gioiTinh = String.valueOf(comboBox_gioiTinh.getSelectedItem());
        
        String ngaySinh = txt_ngaySinh.getText();
        
        String soCMT = txt_soCMT.getText();
        
        String soDienThoai = txt_dienThoai.getText();
        
        String email = txt_email.getText(); 
        
        String phuongCuTru = String.valueOf(comboBox_phuong.getSelectedItem());
        
        String diaChi = txt_diaChi.getText();
        
        String soCongTo = txt_soCongTo.getText();
        
        String donGiaDien = "0";
        
        if(radioButton_tinhTheoDonGia.isSelected())
            donGiaDien = txt_donGiaDien.getText();
        
        String chiSoHienTai = txt_chiSoHienTai.getText();
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c = Calendar.getInstance();
        Date date = c.getTime();
        String dateNow = df.format(date);
        
        if(gioiTinh == "Chưa chọn") {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn giới tính", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(phuongCuTru == "Chưa chọn") {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn phường cư trú", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(hoTen, Check_String.STRING)) {
            JOptionPane.showMessageDialog(this, "Họ tên không được chứa số hay ký tự đặc biệt !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(ngaySinh, Check_String.DATE__YYY_MM_DD)){
            JOptionPane.showMessageDialog(this, "Ngày Tháng Năm sinh phải theo mẫu \"Năm-Tháng-Ngày\" !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(soDienThoai, Check_String.PHONE_NUMBER)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại chỉ được chứa số và có độ dài 10 chữ số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(email, Check_String.EMAIL)) {
            JOptionPane.showMessageDialog(this, "Sai cấu trúc Email !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(soCongTo, Check_String.NUMBER)) {
            JOptionPane.showMessageDialog(this, "Số công tơ chỉ được chứa số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(soCMT, Check_String.NUMBER)) {
            JOptionPane.showMessageDialog(this, "Số chứng minh/căn cước phải là số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(donGiaDien, Check_String.NUMBER)) {
            JOptionPane.showMessageDialog(this, "Đơn giá điện phải là số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(chiSoHienTai, Check_String.NUMBER)) {
            JOptionPane.showMessageDialog(this, "Chỉ số điện phải là số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else {
            
            if(DB_MySQL.select(new String[] {"*"}, "khachHang", "soCongTo = " + txt_soCongTo.getText()) == null) {
                
                String table = "khachHang";
        
                String column[] = new String[] {"hoTen", "gioiTinh", "ngaySinh", "soCMT", "soDienThoai", "email", "diaChi", "tenPhuong", "soCongTo", "donGia"};

                String values[] = new String[] {hoTen, gioiTinh, ngaySinh, soCMT, soDienThoai, email, diaChi, phuongCuTru, soCongTo, donGiaDien};

                if(DB_MySQL.insert(table, column, values)) {

                    String idKH = DB_MySQL.select(new String[] {"idKH"}, "khachhang", "soCongTo = " + soCongTo)[0][0];
                    if(DB_MySQL.insert("datenhapchiso", new String[] {"idKH", "chiSoMoi", "chiSoCu"}, new String[] {idKH, "0000-00-00", dateNow}) && DB_MySQL.insert("chisodien", new String[] {"idKH", "chiSoMoi", "chiSoCu"}, new String[] {idKH, "0", chiSoHienTai}))
                       JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE); 
                }
                else 
                    JOptionPane.showMessageDialog(this, "Thêm khách hàng không thành công !", "Lỗi", JOptionPane.ERROR_MESSAGE);
                
            } else 
                JOptionPane.showMessageDialog(this, "Số công tơ bị trùng !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            
        }
        
    }//GEN-LAST:event_button_taoActionPerformed

    private void radioButton_tinhTheoDonGiaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_radioButton_tinhTheoDonGiaPropertyChange
        
    }//GEN-LAST:event_radioButton_tinhTheoDonGiaPropertyChange

    private void radioButton_tinhTheoDonGiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButton_tinhTheoDonGiaItemStateChanged
        txt_donGiaDien.setEnabled(true);
    }//GEN-LAST:event_radioButton_tinhTheoDonGiaItemStateChanged

    private void radioButton_tinhTheoBacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButton_tinhTheoBacItemStateChanged
        txt_donGiaDien.setEnabled(false);
    }//GEN-LAST:event_radioButton_tinhTheoBacItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(them_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(them_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(them_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(them_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new them_khachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_dong;
    private javax.swing.JButton button_tao;
    private javax.swing.JComboBox<String> comboBox_gioiTinh;
    private javax.swing.JComboBox<String> comboBox_phuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton radioButton_tinhTheoBac;
    private javax.swing.JRadioButton radioButton_tinhTheoDonGia;
    private javax.swing.JTextField txt_chiSoHienTai;
    private javax.swing.JTextArea txt_diaChi;
    private javax.swing.JTextField txt_dienThoai;
    private javax.swing.JTextField txt_donGiaDien;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JTextField txt_soCMT;
    private javax.swing.JTextField txt_soCongTo;
    // End of variables declaration//GEN-END:variables

}
