/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl.java;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ba _Tran
 */
public class thongtin_chiSoDien extends javax.swing.JFrame {
    
    private String idKH;
    
    private static thongtin_chiSoDien frameThongTinChiSoDien;

    public static void openFrameThongTinChiSoDien(String idKH) {
        frameThongTinChiSoDien = new thongtin_chiSoDien();
        frameThongTinChiSoDien.setVisible(true);
        frameThongTinChiSoDien.idKH = idKH;
        frameThongTinChiSoDien.showThongTin(idKH);
    }
    
    private void showThongTin(String idKH) {
        
        String columns[] = new String[] {"hoTen", "soCongTo", "soCMT", "soDienThoai", "email", "tenPhuong", "diaChi", "chisodien.chiSoMoi", "datenhapchiso.chiSoMoi"};
        String table = "khachhang, chisodien, datenhapchiso";
        String where = "khachhang.idKH = chisodien.idKH AND chisodien.idKH = datenhapchiso.idKH AND khachhang.idKH = " + idKH;
        
        String data[][] = DB_MySQL.select(columns, table, where);
        label_maKH.setText(idKH);
        label_hoTen.setText(data[0][0]);
        label_soCongTo.setText(data[0][1]);
        label_soCMT.setText(data[0][2]);
        label_soDienThoai.setText(data[0][3]);
        label_email.setText(data[0][4]);
        label_phuongCuTru.setText(data[0][5]);
        label_diaChi.setText(data[0][6]);
        txt_chiSoMoi.setText(data[0][7]);
        txt_chiSoMoi.setEnabled(false);
        label_thoiGianNhap.setText(data[0][8]);
        
    }
    
    /**
     * Creates new form thongtin_chiSoDien
     */
    public thongtin_chiSoDien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        label_hoTen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_soCongTo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_soCMT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_soDienThoai = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_phuongCuTru = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_diaChi = new javax.swing.JLabel();
        label_maKH = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_chiSoMoi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        label_thoiGianNhap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Thông tin chỉ số điện");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Họ tên:");

        label_hoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_hoTen.setText("...");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Số công tơ:");

        label_soCongTo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_soCongTo.setText("...");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Số chứng minh thư:");

        label_soCMT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_soCMT.setText("...");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Số điện thoại:");

        label_soDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_soDienThoai.setText("...");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Email:");

        label_email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_email.setText("...");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Phường cư trú:");

        label_phuongCuTru.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_phuongCuTru.setText("...");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        label_diaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_diaChi.setText("...");

        label_maKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_maKH.setText("...");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Mã khách hàng:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Chỉ số mới:");

        txt_chiSoMoi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("kWh");

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hủy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Đóng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Thời gian nhập:");

        label_thoiGianNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_thoiGianNhap.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_maKH))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_hoTen)
                                    .addComponent(label_soCongTo)
                                    .addComponent(label_soCMT)
                                    .addComponent(label_soDienThoai)
                                    .addComponent(label_email)
                                    .addComponent(label_phuongCuTru)
                                    .addComponent(label_diaChi)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_chiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addComponent(label_thoiGianNhap))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(label_maKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_hoTen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_soCongTo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(label_soCMT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(label_soDienThoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_email))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(label_phuongCuTru))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(label_diaChi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_chiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(label_thoiGianNhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(Check_String.check(txt_chiSoMoi.getText(), Check_String.NUMBER)) {
         
            float chiSoCu = Float.parseFloat(DB_MySQL.select(new String[] {"chiSoCu"}, "chisodien", "idKH = " + label_maKH.getText())[0][0]);
        
            if(Float.parseFloat(txt_chiSoMoi.getText()) > 0 && Float.parseFloat(txt_chiSoMoi.getText()) > chiSoCu) {

                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn lưu thay đổi ?", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                    String tables = "chisodien, datenhapchiso";
                    String columns[] = new String[] {"chisodien.chiSoMoi", "datenhapchiso.chiSoMoi"};
                    String where = "chisodien.idKH = datenhapchiso.idKH AND chisodien.idKH = " + label_maKH.getText();

                    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    Calendar c = Calendar.getInstance();
                    Date date = c.getTime();
                    String dateNow = df.format(date);

                    String values[] = new String[] {txt_chiSoMoi.getText(), dateNow};

                    DB_MySQL.update(tables, columns, values, where);

                    JOptionPane.showMessageDialog(this, "Cập nhật chỉ số điện thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                    showThongTin(frameThongTinChiSoDien.idKH);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Chỉ số mới phải > 0 và > " + chiSoCu + " (chỉ số cũ)", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            
        } else 
            JOptionPane.showMessageDialog(this, "Chỉ số mới phải là số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        frameThongTinChiSoDien.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showThongTin(frameThongTinChiSoDien.idKH);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txt_chiSoMoi.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thongtin_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thongtin_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thongtin_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thongtin_chiSoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thongtin_chiSoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_diaChi;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_hoTen;
    private javax.swing.JLabel label_maKH;
    private javax.swing.JLabel label_phuongCuTru;
    private javax.swing.JLabel label_soCMT;
    private javax.swing.JLabel label_soCongTo;
    private javax.swing.JLabel label_soDienThoai;
    private javax.swing.JLabel label_thoiGianNhap;
    private javax.swing.JTextField txt_chiSoMoi;
    // End of variables declaration//GEN-END:variables
}
