/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl.java;

import javax.swing.JOptionPane;

/**
 *
 * @author Ba _Tran
 */
public class thongtin_khachHang extends javax.swing.JFrame {

    private static thongtin_khachHang frameThongTinKH;
    
    public static void openFrameThongTinKH(String idKH) {
        
        frameThongTinKH = new thongtin_khachHang();
        frameThongTinKH.setVisible(true);
        frameThongTinKH.showThongTin(idKH);
    }
    
    public void showThongTin(String idKH) {
        
        String columns[] = new String[] {"hoTen", "gioiTinh", "ngaySinh", "soCMT", "soDienThoai", "email", "tenPhuong", "diaChi", "soCongTo"};
        String table = "khachhang";
        String where = "idKH = " + idKH;
        
        String dataKH[][] = DB_MySQL.select(columns, table, where);
        
        columns = new String[] {"thangNam", "chiSoMoi", "chiSoCu", "dateThanhToan"};
        table = "lichsugiaodich";
        where = "idKH = " + idKH;
        
        String dataLS[][] = DB_MySQL.select(columns, table, where);
        
        // Hiển thị thông tin khách hàng
        label_maKH.setText(idKH);
        txt_hoTen.setText(dataKH[0][0]);
        comboBox_gioiTinh.setSelectedItem(dataKH[0][1]);
        txt_ngaySinh.setText(dataKH[0][2]);
        txt_soCMT.setText(dataKH[0][3]);
        txt_dienThoai.setText(dataKH[0][4]);
        txt_email.setText(dataKH[0][5]);
        comboBox_phuongCuTru.setSelectedItem(dataKH[0][6]);
        txt_diaChi.setText(dataKH[0][7]);
        txt_soCongTo.setText(dataKH[0][8]);
        
        // Hiểm thị lịch sử thanh toán
        Display_JTable.setTable(table_lichSuThanhToan);
        Display_JTable.setColumn(new String[]{"STT", "Điện thang/năm", "Chỉ số mới (kWh)", "Chỉ số cũ (kWh)", "Thời gian thanh toán"});
        Display_JTable.displayTable_Data2D(dataLS, true);
    }
    
    public thongtin_khachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        label_maKH = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboBox_phuongCuTru = new javax.swing.JComboBox<>();
        txt_hoTen = new javax.swing.JTextField();
        txt_ngaySinh = new javax.swing.JTextField();
        txt_soCMT = new javax.swing.JTextField();
        txt_dienThoai = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_diaChi = new javax.swing.JTextArea();
        button_suaHuy = new javax.swing.JButton();
        button_luu = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        comboBox_gioiTinh = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_soCongTo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_lichSuThanhToan = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Họ tên:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Giới tính:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Số chứng minh thư:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Số điện thoại:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Phường cư trú:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Thông tin khách hàng");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Mã khách hàng:");

        label_maKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_maKH.setText("001");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Ngày sinh:");

        comboBox_phuongCuTru.setEditable(true);
        comboBox_phuongCuTru.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboBox_phuongCuTru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cầu Diễn", "Đại Mỗ", "Mễ Trì", "Mỹ Đình 1", "Mỹ Đình 2", "Phương Canh", "Phú Đô", "Trung Văn", "Tây Mỗ", "Xuân Phương" }));
        comboBox_phuongCuTru.setEnabled(false);
        comboBox_phuongCuTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_phuongCuTruActionPerformed(evt);
            }
        });

        txt_hoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_hoTen.setEnabled(false);

        txt_ngaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_ngaySinh.setEnabled(false);

        txt_soCMT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_soCMT.setEnabled(false);
        txt_soCMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soCMTActionPerformed(evt);
            }
        });

        txt_dienThoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_dienThoai.setEnabled(false);
        txt_dienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dienThoaiActionPerformed(evt);
            }
        });

        txt_email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_email.setEnabled(false);

        txt_diaChi.setColumns(20);
        txt_diaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_diaChi.setRows(3);
        txt_diaChi.setEnabled(false);
        jScrollPane1.setViewportView(txt_diaChi);

        button_suaHuy.setText("Sửa");
        button_suaHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_suaHuyActionPerformed(evt);
            }
        });

        button_luu.setText("Lưu");
        button_luu.setEnabled(false);
        button_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_luuActionPerformed(evt);
            }
        });

        jButton3.setText("Đóng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        comboBox_gioiTinh.setEditable(true);
        comboBox_gioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboBox_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        comboBox_gioiTinh.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("yyyy-mm-dd");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Số công tơ:");

        txt_soCongTo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_soCongTo.setEnabled(false);

        table_lichSuThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Điện Tháng/Năm", "Chỉ số mới (kWh)", "Chỉ số cũ (kWh)", "Thời gian thanh toán"
            }
        ));
        jScrollPane2.setViewportView(table_lichSuThanhToan);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel12.setText("Lịch sử thanh toán");

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 348, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                        .addComponent(txt_dienThoai, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_soCMT, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txt_soCongTo, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(120, 120, 120)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_maKH)
                                        .addComponent(comboBox_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox_phuongCuTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(button_suaHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(button_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(label_maKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBox_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_soCMT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_dienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBox_phuongCuTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soCongTo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_suaHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_suaHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_suaHuyActionPerformed
        
        if(button_suaHuy.getText() == "Sửa") {
            
            button_suaHuy.setText("Hủy");
            button_luu.setEnabled(true);
            
            label_maKH.setEnabled(true);
            txt_hoTen.setEnabled(true);
            comboBox_gioiTinh.setEnabled(true);
            txt_ngaySinh.setEnabled(true);
            txt_soCMT.setEnabled(true);
            txt_dienThoai.setEnabled(true);
            txt_email.setEnabled(true);
            comboBox_phuongCuTru.setEnabled(true);
            txt_diaChi.setEnabled(true);
            txt_soCongTo.setEnabled(true);
            
        } else if(button_suaHuy.getText() == "Hủy") {
            
            button_suaHuy.setText("Sửa");
            button_luu.setEnabled(false);
            showThongTin(label_maKH.getText());
            
            label_maKH.setEnabled(false);
            txt_hoTen.setEnabled(false);
            comboBox_gioiTinh.setEnabled(false);
            txt_ngaySinh.setEnabled(false);
            txt_soCMT.setEnabled(false);
            txt_dienThoai.setEnabled(false);
            txt_email.setEnabled(false);
            comboBox_phuongCuTru.setEnabled(false);
            txt_diaChi.setEnabled(false);
            txt_soCongTo.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_button_suaHuyActionPerformed

    private void button_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_luuActionPerformed
        
        String hoTen = txt_hoTen.getText();
        
        String gioiTinh = String.valueOf(comboBox_gioiTinh.getSelectedItem());
        
        String ngaySinh = txt_ngaySinh.getText();
        
        String soCMT = txt_soCMT.getText();
        
        String soDienThoai = txt_dienThoai.getText();
        
        String email = txt_email.getText();
        
        String soCongTo = txt_soCongTo.getText();
        
        if(! Check_String.check(hoTen, Check_String.STRING)) {
            JOptionPane.showMessageDialog(this, "Họ tên không được chứa số hay ký tự đặc biệt !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(ngaySinh, Check_String.DATE__YYY_MM_DD)){
            JOptionPane.showMessageDialog(this, "Ngày Tháng Năm sinh phải theo mẫu \"Năm-Tháng-Ngày\" !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(soDienThoai, Check_String.PHONE_NUMBER)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại chỉ được chứa số và có độ dài 10 chữ số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(email, Check_String.EMAIL)) {
            JOptionPane.showMessageDialog(this, "Sai cấu trúc Email !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(soCongTo, Check_String.NUMBER)) {
            JOptionPane.showMessageDialog(this, "Số công tơ chỉ được chứa số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if(! Check_String.check(soCMT, Check_String.NUMBER)) {
            JOptionPane.showMessageDialog(this, "Số chứng minh/căn cước phải là số !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else {
            
            if(DB_MySQL.select(new String[] {"*"}, "khachHang", "soCongTo = " + txt_soCongTo.getText()) == null) {
                
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn lưu thông tin khách hàng", "Xác nhận", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {

                   String columns[] = new String[] {"hoTen", "gioiTinh", "ngaySinh", "soCMT", "soDienThoai", "email", "tenPhuong", "diaChi", "soCongTo"};
                   String table = "khachhang";
                   String values[] = new String[] {txt_hoTen.getText(), String.valueOf(comboBox_gioiTinh.getSelectedItem()), txt_ngaySinh.getText(), txt_soCMT.getText(), txt_dienThoai.getText(), txt_email.getText(), String.valueOf(comboBox_phuongCuTru.getSelectedItem()), txt_diaChi.getText(), txt_soCongTo.getText()};
                   String where = "idKH = " + label_maKH.getText();

                   DB_MySQL.update(table, columns, values, where);

                   label_maKH.setEnabled(false);
                   txt_hoTen.setEnabled(false);
                   comboBox_gioiTinh.setEnabled(false);
                   txt_ngaySinh.setEnabled(false);
                   txt_soCMT.setEnabled(false);
                   txt_dienThoai.setEnabled(false);
                   txt_email.setEnabled(false);
                   comboBox_phuongCuTru.setEnabled(false);
                   txt_diaChi.setEnabled(false);
                   txt_soCongTo.setEnabled(false);

                   button_suaHuy.setText("Sửa");
                   button_luu.setEnabled(false);
                   showThongTin(label_maKH.getText());

                }   
                
            } else
                JOptionPane.showMessageDialog(this, "Số công tơ bị trùng !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_button_luuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        frameThongTinKH.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_soCMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soCMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soCMTActionPerformed

    private void txt_dienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dienThoaiActionPerformed

    private void comboBox_phuongCuTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_phuongCuTruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_phuongCuTruActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn lưu thông tin khách hàng", "Xác nhận", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {
            
            String where = "idKH = " + label_maKH.getText();
            
            DB_MySQL.delete("chisodien", where);
            DB_MySQL.delete("datenhapchiso", where);
            DB_MySQL.delete("lichsugiaodich", where);
            DB_MySQL.delete("khachhang", where);
            
            frameThongTinKH.setVisible(false);
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thongtin_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thongtin_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thongtin_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thongtin_khachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thongtin_khachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_luu;
    private javax.swing.JButton button_suaHuy;
    private javax.swing.JComboBox<String> comboBox_gioiTinh;
    private javax.swing.JComboBox<String> comboBox_phuongCuTru;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_maKH;
    private javax.swing.JTable table_lichSuThanhToan;
    private javax.swing.JTextArea txt_diaChi;
    private javax.swing.JTextField txt_dienThoai;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JTextField txt_soCMT;
    private javax.swing.JTextField txt_soCongTo;
    // End of variables declaration//GEN-END:variables
}
